services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: checkmeasure-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app                    # Code (for hot reload)
      - ./uploads:/app/uploads           # Persistent PDF storage
      - ./temp:/app/temp                 # Temporary processing files
      - backend-logs:/app/logs           # Logs using named volume
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - checkmeasure-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: checkmeasure-frontend
    ports:
      - "3000:3000"
    environment:
      # - REACT_APP_API_URL=http://backend:8000  # Commented out - use localhost:8000 default
      - CHOKIDAR_USEPOLLING=true         # For file watching in Docker
    volumes:
      - ./frontend:/app
      - /app/node_modules                # Prevent node_modules override
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - checkmeasure-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  checkmeasure-network:
    driver: bridge

volumes:
  backend-logs:
    driver: local