services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: checkmeasure/backend:latest
    container_name: checkmeasure-backend-prod
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - prod-logs:/app/logs
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - checkmeasure-network
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: checkmeasure/frontend:latest
    container_name: checkmeasure-frontend-prod
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: always
    networks:
      - checkmeasure-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  nginx:
    image: nginx:alpine
    container_name: checkmeasure-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - checkmeasure-network

networks:
  checkmeasure-network:
    driver: bridge

volumes:
  prod-logs:
    driver: local